CREATE TABLE data_engineering.strava_dev.strava_athlete_activities_cleanse (
  id BIGINT COMMENT 'A unique identifier for each athlete activity recorded on the Strava platform.',
  athlete_id INT COMMENT 'The identifier for the athlete who performed the activity, linking to their profile.',
  athlete_count INT COMMENT 'The number of athletes who participated in the activity, useful for group events or challenges.',
  average_cadence DOUBLE COMMENT 'Represents the average number of steps or pedal strokes per minute during the activity.',
  average_speed DOUBLE COMMENT 'The average speed achieved during the activity, providing insight into performance levels.',
  comment_count INT COMMENT 'The total number of comments made on the activity, indicating engagement from the community.',
  is_commute BOOLEAN COMMENT 'Indicates whether the activity was classified as a commute, helping to differentiate between training and travel.',
  device_name STRING COMMENT 'The name of the device used to record the activity, which can provide context on the data quality.',
  display_hide_heartrate_option BOOLEAN COMMENT 'A flag indicating whether the heart rate data is hidden from public view.',
  distance DOUBLE COMMENT 'The total distance covered during the activity, a key metric for performance analysis.',
  elapsed_time DOUBLE COMMENT 'The total time taken for the activity, including any stops, useful for understanding pacing.',
  elev_high DOUBLE COMMENT 'The highest elevation reached during the activity, which can be important for assessing difficulty.',
  elev_low DOUBLE COMMENT 'The lowest elevation reached during the activity, providing context for elevation gain.',
  external_id STRING COMMENT 'An identifier from an external system, which can be used for integration with other platforms.',
  is_flagged BOOLEAN COMMENT 'Indicates whether the activity has been flagged for review, which may affect its visibility.',
  is_from_accepted_tag BOOLEAN COMMENT 'Shows if the activity was recorded with an accepted tag, which can influence categorization.',
  has_heartrate BOOLEAN COMMENT 'Indicates whether heart rate data was recorded during the activity, relevant for performance metrics.',
  has_kudoed BOOLEAN COMMENT 'A flag indicating if the athlete has received kudos for the activity, reflecting community support.',
  is_heartrate_opt_out BOOLEAN COMMENT 'Indicates whether the athlete opted out of sharing heart rate data, affecting data completeness.',
  kudos_count INT COMMENT 'The total number of kudos received for the activity, serving as a measure of community engagement.',
  is_manual BOOLEAN COMMENT 'Indicates whether the activity was manually entered rather than automatically recorded.',
  map_id STRING COMMENT 'An identifier for the map associated with the activity, useful for visualizing the route taken.',
  max_speed DOUBLE COMMENT 'The maximum speed achieved during the activity, providing insight into peak performance.',
  moving_time DOUBLE COMMENT 'The total time spent moving during the activity, excluding any stops.',
  name STRING COMMENT 'The name given to the activity by the athlete, which can provide context or personal significance.',
  photo_count INT COMMENT 'The number of photos associated with the activity, indicating the level of documentation.',
  pr_count INT COMMENT 'The number of personal records set during the activity, highlighting achievements.',
  is_private BOOLEAN COMMENT 'Indicates whether the activity is marked as private, affecting its visibility to others.',
  resource_state INT COMMENT 'Represents the state of the resource, which can indicate its availability or status.',
  sport_type STRING COMMENT 'The type of sport or activity performed, essential for categorizing the data.',
  start_date TIMESTAMP COMMENT 'The timestamp indicating when the activity started, useful for chronological analysis.',
  start_date_local TIMESTAMP COMMENT 'The local timestamp for when the activity started, providing context for time zones.',
  timezone STRING COMMENT 'The time zone in which the activity was recorded, important for accurate time representation.',
  total_elevation_gain DOUBLE COMMENT 'The total elevation gain during the activity, a critical metric for assessing difficulty.',
  total_photo_count INT COMMENT 'The total number of photos taken during the activity, reflecting the athlete\'s engagement.',
  is_trainer BOOLEAN COMMENT 'Indicates whether the activity was performed on a trainer, which can affect performance metrics.',
  type STRING COMMENT 'The type of activity recorded, which helps in categorizing and analyzing different sports.',
  upload_id STRING COMMENT 'An identifier for the upload session, useful for tracking data submissions.',
  utc_offset INT COMMENT 'The offset from Coordinated Universal Time (UTC) for the activity\'s recorded time.',
  visibility STRING COMMENT 'Indicates the visibility settings for the activity, affecting who can see it.',
  workout_type INT COMMENT 'The type of workout performed, which can provide insights into training focus.',
  run_date DATE COMMENT 'The date on which the activity took place, important for historical analysis.',
  run_time TIMESTAMP COMMENT 'The timestamp for when the activity was recorded, providing precise timing information.')
USING delta
COMMENT 'The table contains data related to athlete activities recorded on the Strava platform. It includes metrics such as distance, speed, elevation gain, and various flags indicating the nature of the activity (e.g., whether it was a commute or manual entry). This data can be used for analyzing athlete performance, understanding activity trends, and evaluating engagement through metrics like kudos and comments.'
CLUSTER BY (run_date)
TBLPROPERTIES (
  'delta.checkpointPolicy' = 'v2',
  'delta.dataSkippingNumIndexedCols' = '100',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.feature.v2Checkpoint' = 'supported',
  'delta.parquet.compression.codec' = 'zstd',
  'delta.writePartitionColumnsToParquet' = 'true')